### ISSUE TITLE
Wrong order of GetServiceResources

### ISSUE THREAD

**Issue by checkelmann** [keptn-sandbox/jenkins-service#2]
Hi,

the order of the parameters is wrong in this Line
https://github.com/keptn-sandbox/jenkins-service/blob/master/jenkinshelper.go#L51

Right now it is: 

`keptnResourceContent, err := resourceHandler.GetServiceResource(keptnEvent.service, keptnEvent.stage, keptnEvent.project, JenkinsConfigFilename)`

but should be
`keptnResourceContent, err := resourceHandler.GetServiceResource(keptnEvent.project, keptnEvent.stage, keptnEvent.service, JenkinsConfigFilename)`

From resourceUtils.go
```
// GetServiceResource retrieves a service resource from the configuration service
func (r *ResourceHandler) GetServiceResource(project string, stage string, service string, resourceURI string) (*models.Resource, error) {
	return r.getResource(r.Scheme + "://" + r.BaseURL + "/v1/project/" + project + "/stage/" + stage + "/service/" + url.QueryEscape(service) + "/resource/" + url.QueryEscape(resourceURI))
}
```

Cheers,

Christian

**Comment by christian-kreuzberger-dtx** [comment]
Please note that this service is no longer maintained and will be archived. I'm closing this issue for now.
